version: "3.9"

services:
  web:
    build: .
    container_name: fitness-app
    command: python app.py
    ports:
      - "5000:5000"
    env_file:
      - .env  # local file with SECRET_KEY, DATABASE_URL, etc.
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app  # optional: mount source for dev with hot reload

  db:
    image: postgres:15
    container_name: flask-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fitness_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
