"""Remove the pk row from programs_exercises mapping table

Revision ID: 0342d1a098d7
Revises: 3eb23f29754f
Create Date: 2025-05-06 12:02:05.787918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0342d1a098d7'
down_revision = '3eb23f29754f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs_exercises', schema=None) as batch_op:
        batch_op.drop_column('pk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
