"""Creating migrations again

Revision ID: 11c3db37a81d
Revises: 
Create Date: 2024-11-07 20:53:33.412490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c3db37a81d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=201),
               existing_nullable=False)
        batch_op.drop_column('short_video')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_video', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.String(length=201),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
